### PR TITLE
docs: ldap support

### PR DESCRIPTION
**Pull request by csh0101**
docs: ldap supports

### CODE REVIEW

**Comment by csh0101** [comment]
connect #293

**Comment by frankzhaopeng** [comment]
> connect #293

Refer to this documentation to link a pull request to an issue.

**Comment by gangb-tech** [comment]
LGTM

**Comment by csh0101** [comment]
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Thanks I will

**Pull request merged**
